// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlrMtSORt-eIQQJfXnRmNaLicV9YXGceI',
    appId: '1:1068589702782:web:5b22cdec3ec474af1f022f',
    messagingSenderId: '1068589702782',
    projectId: 'instagram-flutter-d23ff',
    authDomain: 'instagram-flutter-d23ff.firebaseapp.com',
    storageBucket: 'instagram-flutter-d23ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7RBqFPEx9AwLTFXMDrAf7bWU19PRxsRs',
    appId: '1:1068589702782:android:99e84d4af96d2ef61f022f',
    messagingSenderId: '1068589702782',
    projectId: 'instagram-flutter-d23ff',
    storageBucket: 'instagram-flutter-d23ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBqgi2VneccGcNqZ43zi69jkpuDfI5SU',
    appId: '1:1068589702782:ios:3229fd44feae4ea41f022f',
    messagingSenderId: '1068589702782',
    projectId: 'instagram-flutter-d23ff',
    storageBucket: 'instagram-flutter-d23ff.appspot.com',
    iosClientId: '1068589702782-q90c5ttaflno4kkull5mkntl8cq1sc0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
